# Generated by Django 3.1.7 on 2021-03-19 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predictimage',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
